name: chatgear
main: com.github.mpotacon.chatgear.chatgear
version: 0.5
author: mpotacon
description: Bukkit Chat Plugin
commands:
    ping:
        description: pong
        usage: /<command>
    tell:
        description: send a private message
        usage: /<command>
permissions:
    chatgear.*:
        description: Gives access to all chatgear commands
        children:
            chatgear.tell: true
            chatgear.receive: true
    chatgear.tell:
        description: Allows you to send a private message
        default: op
    chatgear.receive:
        description: Allows you to receive a private message
        default: op