name: chatgear
main: com.github.mpotacon.chatgear.chatgear
version: 0.65
author: mpotacon
description: Bukkit Chat Plugin
commands:
    ping:
        description: pong
        usage: /ping
    tell:
        description: send a private message
        usage: /tell <player> <message> 
    mute:
        description: mutes a player from chat
        usage: /mute <player>    
permissions:
    chatgear.*:
        description: Gives access to all chatgear commands
        children:
            chatgear.tell: true
            chatgear.receive: true
    chatgear.tell:
        description: Allows you to send a private message
        default: true
    chatgear.receive:
        description: Allows you to receive a private message
        default: true
    chatgear.mute:
        description: Allows you to mute a player
        default: op